apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: titan
  name: titan-clusterip
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: titan
  type: ClusterIP
status:
  loadBalancer: {}
